/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#define LOG_TAG "CallbackJNI"
#define ALOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
/* Header for class com_cvtouch_jnilib_Callbacks */

#define NULL 0

#ifndef _Included_com_cvtouch_jnilib_Callbacks
#define _Included_com_cvtouch_jnilib_Callbacks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cvtouch_jnilib_Callbacks
 * Method:    nativeMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_cvtouch_jnilib_Callbacks_nativeMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
